[package]
name = "{{project-name}}"
version = "0.0.0"
authors = ["{{authors}}"]
description = ""
edition = "2021"
rust-version = "1.58"
repository = ""
license = "MulanPSL-2.0"
readme = "README.md"
keywords = []
categories = []

[dependencies]
